services:
  - type: web
    name: flow-fakturace
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: odberna-mista-db
          property: connectionString
