services:
  - type: web
    name: energo-fakturace
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: odberna-mista-db
          property: connectionString
    region: frankfurt
    plan: starter
